package com.smartlearning.backend.service;

import com.smartlearning.backend.model.Task;
import com.smartlearning.backend.repository.TaskRepository;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.*;

@Service
public class TaskService {

    private final TaskRepository repo;

    private SimpMessagingTemplate messagingTemplate;

    public TaskService(TaskRepository repo) {
        this.repo = repo;
    }

    // CREATE TASK (accept email)
    public Task createTask(Task t, String email) {
        t.setOwnerEmail(email);

        if (t.getDueDate() != null &&
                t.getDueDate().isBefore(LocalDate.now().plusDays(2))) {
            t.setPriority("HIGH");
        } else {
            t.setPriority("LOW");
        }

        applySmartLogic(t);
        return repo.save(t);
    }

    // GET ALL TASKS
    public List<Task> getTasksByUser(String email) {
        return repo.findByOwnerEmail(email);
    }

    // COMPLETE TASK
    public Task completeTask(Long id) {
        Task t = repo.findById(id).orElseThrow();
        t.setCompleted(true);
        return repo.save(t);
    }

    // SMART LOGIC ENGINE
    private void applySmartLogic(Task task) {
        setPriority(task);
        categorize(task);
    }

    // PRIORITY LOGIC
    private void setPriority(Task task) {
        if (task.getDueDate() == null) {
            task.setPriority("LOW");
            return;
        }

        long days = LocalDate.now().until(task.getDueDate(), ChronoUnit.DAYS);

        if (days <= 0) task.setPriority("URGENT");
        else if (days <= 1) task.setPriority("HIGH");
        else if (days <= 3) task.setPriority("MEDIUM");
        else task.setPriority("LOW");
    }

    // CATEGORY LOGIC
    private void categorize(Task task) {
        if (task.getTitle() == null) return;

        String t = task.getTitle().toLowerCase();

//        if (t.contains("study") || t.contains("exam")) {
//            task.setCategory("ACADEMIC");
//        } else if (t.contains("meeting") || t.contains("project")) {
//            task.setCategory("WORK");
//        } else {
//            task.setCategory("PERSONAL");
//        }
    }

    // STATS
    public Map<String, Object> getStatsByUser(String email) {

        List<Task> all = repo.findByOwnerEmail(email);

        long completed = all.stream().filter(Task::isCompleted).count();
        long pending = all.size() - completed;

        int percent = all.isEmpty()
                ? 0
                : (int) ((completed * 100) / all.size());

        Map<String, Object> stats = new HashMap<>();
        stats.put("total", all.size());
        stats.put("completed", completed);
        stats.put("pending", pending);
        stats.put("progress", percent);

        return stats;
    }

    // AI SUGGESTION
    public Task generateSuggestion() {

        String[] suggestions = {
                "Review notes",
                "Plan tomorrow",
                "Complete pending work",
                "Revise key topic",
                "Organize tasks"
        };

        String title = suggestions[new Random().nextInt(suggestions.length)];

        Task t = new Task();
        t.setTitle(title);
        t.setAutoGenerated(true);
        t.setSuggestionSource("AI");
        t.setDueDate(LocalDate.now());

        t.setOwnerEmail("system");

        applySmartLogic(t);

        return repo.save(t);
    }

    // NOTIFICATIONS (DUE SOON)
    public List<Task> getDueSoonTasks(String email) {
        List<Task> tasks = repo.findByOwnerEmail(email);
        List<Task> dueSoon = new ArrayList<>();

        for (Task t : tasks) {
            if (t.getDueDate() != null && !t.isNotificationDismissed() && !t.isCompleted()) {
                long days = LocalDate.now().until(t.getDueDate(), ChronoUnit.DAYS);
                if (days <= 1) {
                    if (!t.isNotified()) {
                        t.setNotified(true);
                        repo.save(t);
                    }
                    dueSoon.add(t);
                }
            }
        }
        return dueSoon;
    }

    // MARK NOTIFICATION AS READ
    public Task markNotificationRead(Long id) {
        Task t = repo.findById(id).orElseThrow();
        t.setNotificationRead(true);
        return repo.save(t);
    }

    // DISMISS/DELETE NOTIFICATION
    public Task dismissNotification(Long id) {
        Task t = repo.findById(id).orElseThrow();
        t.setNotificationDismissed(true);
        return repo.save(t);
    }

    public void sendNotification(Task task) {
        messagingTemplate.convertAndSend(
                "/topic/notifications/" + task.getOwnerEmail(),
                task
        );
    }

    // UPDATE TASK
    public Task updateTask(Long id, Task updated) {
        Task existing = repo.findById(id).orElseThrow();

        existing.setTitle(updated.getTitle());
        existing.setDueDate(updated.getDueDate());
        existing.setCompleted(updated.isCompleted());

        existing.setCategory(updated.getCategory());

        existing.setNotified(updated.isNotified());

        setPriority(existing);
        return repo.save(existing);
    }

    // DELETE EXPIRED TASKS
    public void deleteExpiredTasks() {
        List<Task> tasks = repo.findAll();
        LocalDate today = LocalDate.now();

        for (Task t : tasks) {
            if (t.getDueDate() != null && t.getDueDate().isBefore(today)) {
                repo.delete(t);
            }
        }
    }

    // DELETE TASK
    public void deleteTask(Long id) {
        repo.deleteById(id);
    }

    public void processAllUsersNotifications() {
        List<String> users = repo.findAllDistinctUserEmails();
        for (String email : users) {
            getDueSoonTasks(email);
        }
    }
}