spring.application.name=Backend

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/smartLearning
spring.datasource.username=root
spring.datasource.password=97271
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SERVER
server.port=8086

# GEMINI
gemini.api.key=${GEMINI_API_KEY:AIzaSyDXahjZHZfYCmihDLIxgcHs96-Ozu_x80A}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}

# SPRING SECURITY (basic login)
spring.security.user.name=admin
spring.security.user.password=1234

# EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=p.y.madhushan@gmail.com
spring.mail.password=orfj zhpd hlqy bdrx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#-------------------------------------------------------------------
spring.jpa.open-in-view=false

# Multipart upload policy
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

